#ifndef __OUTPUT_H
#define __OUTPUT_H
#include "flash.h"

#define FLASH_HANDLE_TIME 50
#define DATA_SIZE 2
#define FLASH_MENBER 22

#define MODEL_ADDR             (0x08000000 + 1024 * 123)   /* 扇区123 */



/* 主存储地址 */
#define A_SET_TEMP_ADDRESS (0x08000000 + 1024 * 124)
#define A_SET_AIR_ADDRESS A_SET_TEMP_ADDRESS + DATA_SIZE
#define A_CH1_SET_TEMP_ADDRESS A_SET_AIR_ADDRESS + DATA_SIZE
#define A_CH1_SET_WIND_ADDRESS A_CH1_SET_TEMP_ADDRESS + DATA_SIZE
#define A_CH2_SET_TEMP_ADDRESS A_CH1_SET_WIND_ADDRESS + DATA_SIZE
#define A_CH2_SET_WIND_ADDRESS A_CH2_SET_TEMP_ADDRESS + DATA_SIZE
#define A_CH3_SET_TEMP_ADDRESS A_CH2_SET_WIND_ADDRESS + DATA_SIZE
#define A_CH3_SET_WIND_ADDRESS A_CH3_SET_TEMP_ADDRESS + DATA_SIZE
#define A_WORK_MODE_ADDRESS A_CH3_SET_WIND_ADDRESS + DATA_SIZE
#define A_TEMP_UNIT_ADDRESS A_WORK_MODE_ADDRESS + DATA_SIZE
#define A_SPEAK_MODE_ADDRESS A_TEMP_UNIT_ADDRESS + DATA_SIZE
#define A_LANGUAGE_MODE_ADDRESS A_SPEAK_MODE_ADDRESS + DATA_SIZE
#define A_CAL_DATA_ADDRESS A_LANGUAGE_MODE_ADDRESS + DATA_SIZE
#define A_DISPLAY_LOCK_MODE_ADDRESS A_CAL_DATA_ADDRESS + DATA_SIZE
#define A_SLEEP_MODE_ADDRESS A_DISPLAY_LOCK_MODE_ADDRESS + DATA_SIZE
#define A_RUN_MODE_ADDRESS A_SLEEP_MODE_ADDRESS + DATA_SIZE
#define A_LONGKEY_MODE_ADDRESS A_RUN_MODE_ADDRESS + DATA_SIZE
#define A_SHORTKEY_MODE_ADDRESS A_LONGKEY_MODE_ADDRESS + DATA_SIZE
#define A_ADJUSTKEY_MODE_ADDRESS A_SHORTKEY_MODE_ADDRESS + DATA_SIZE
#define A_COLD_WIND_DATA A_ADJUSTKEY_MODE_ADDRESS + DATA_SIZE
#define A_FLASH_VERSION_ADDRESS A_COLD_WIND_DATA + DATA_SIZE

/* 备份地址 */
#define B_SET_TEMP_ADDRESS (0x08000000 + 1024 * 126)
#define B_SET_AIR_ADDRESS B_SET_TEMP_ADDRESS + DATA_SIZE
#define B_CH1_SET_TEMP_ADDRESS B_SET_AIR_ADDRESS + DATA_SIZE
#define B_CH1_SET_WIND_ADDRESS B_CH1_SET_TEMP_ADDRESS + DATA_SIZE
#define B_CH2_SET_TEMP_ADDRESS B_CH1_SET_WIND_ADDRESS + DATA_SIZE
#define B_CH2_SET_WIND_ADDRESS B_CH2_SET_TEMP_ADDRESS + DATA_SIZE
#define B_CH3_SET_TEMP_ADDRESS B_CH2_SET_WIND_ADDRESS + DATA_SIZE
#define B_CH3_SET_WIND_ADDRESS B_CH3_SET_TEMP_ADDRESS + DATA_SIZE
#define B_WORK_MODE_ADDRESS B_CH3_SET_WIND_ADDRESS + DATA_SIZE
#define B_TEMP_UNIT_ADDRESS B_WORK_MODE_ADDRESS + DATA_SIZE
#define B_SPEAK_MODE_ADDRESS B_TEMP_UNIT_ADDRESS + DATA_SIZE
#define B_LANGUAGE_MODE_ADDRESS B_SPEAK_MODE_ADDRESS + DATA_SIZE
#define B_CAL_DATA_ADDRESS B_LANGUAGE_MODE_ADDRESS + DATA_SIZE
#define B_DISPLAY_LOCK_MODE_ADDRESS B_CAL_DATA_ADDRESS + DATA_SIZE
#define B_SLEEP_MODE_ADDRESS B_DISPLAY_LOCK_MODE_ADDRESS + DATA_SIZE
#define B_RUN_MODE_ADDRESS B_SLEEP_MODE_ADDRESS + DATA_SIZE
#define B_LONGKEY_MODE_ADDRESS B_RUN_MODE_ADDRESS + DATA_SIZE
#define B_SHORTKEY_MODE_ADDRESS B_LONGKEY_MODE_ADDRESS + DATA_SIZE
#define B_ADJUSTKEY_MODE_ADDRESS B_SHORTKEY_MODE_ADDRESS + DATA_SIZE
#define B_COLD_WIND_DATA B_ADJUSTKEY_MODE_ADDRESS + DATA_SIZE
#define B_FLASH_VERSION_ADDRESS B_COLD_WIND_DATA + DATA_SIZE
typedef enum
{
    FLASH_START = 0,
    FLASH_HANDLE_DATA,
    FLASH_GENERAL_DATA,
    FLASH_FINSH,
} flash_state_t;

typedef struct
{
    flash_state_t state;
} flash_handle_t;

void FlashProc(void);

#endif
